### ISSUE TITLE
is it possible to connect to a local database with this approach?

### ISSUE THREAD

**Issue by urswilke** [hrbrmstr/webr-vite-duckdb#2]
Not an issue but a question: Is it possible to connect to a local database from the browser with this approach? 
In other words, instead of loading tabular data with `FileAttachment` like in this repo, I'd like to connect to a local Postgresql database and read a table from there.

**Comment by hrbrmstr** [comment]
Not in the forseeable future. DuckDB-Wasm extensions have a few inherent
limitations; and, it is not possible to communicate with native executables
living on your machine, which is actually required postgres scanner
extension. Sigh.

**Comment by urswilke** [comment]
Thanks a lot for the response! This saves me from losing more time trying and googling. When I was trying to implement something, I was also running into errors related to postgres scanner that I didn't really understand. Now, this explains everything...

**Comment by urswilke** [comment]
But it is super cool nonetheless, how easy it is to setup and use a duckdb database in the browser by just passing an array of objects!
